data:
  dataset: "dvs128gesture"
  root: "/home/haohq/datasets/DVS128Gesture"
  count: 2048
  stride: 1024
  input_len: 1024
  rep_len: 128
  patch_size: 32
  train_split: 0.8
  shuffle: True
  num_workers: 32

models:
  tokenizer: "event_tokenizer"
  model: "rwkv4"

training:
  batch_size: 64
  device_id: 0
  nepochs: 20
  lr: 0.001
  output_dir: "outputs/pretrain_rwkv4"
  save_freq: 10
  resume: False
  optimizer: "adam"
  scheduler:
    step_size: 10
    gamma: 0.1

loss:
  loss_fn: "l2"
  pred_frame: True
  pred_ts: True
  pred_next_frame: True

dist:
  dist_url: "env://"
  backend: "gloo"

misc:
  seed: 2024