# data
dataset: "dvs128gesture"
root: "datasets/DVS128Gesture"
patch_size: 32
count: 4096
stride: 4096
inverse: False
train_split: 0.8
val_split: 0.1
shuffle: True
num_workers: 16

# models
encoder: "rwkv4"
tokenizer: "event_tokenizer"

# training
device_id: 0
batch_size: 16
nepochs: 100
lr: 0.001
output_dir: "outputs/pretrain"
save_freq: 1
resume: False
optimizer: "adam"
input_len: 2048
repr_len: 256

# loss
loss_fn: "l2"
use_frame_target: True
use_next_frame_target: True
use_ts_target: False
ts_tau: 0.1

# dist
dist_url: "env://"
backend: "gloo"

# random
seed: 2024

