# data
train_split: 0.8
val_split: 0.1
shuffle: True
num_workers: 32
batch_size: 256


# models
decoder: 'vit'

# pretrain
checkpoint: '/home/haohq/multi-representation-ssl/outputs/pretrain/rwkv4_dvs128gesture_20241124-213306/checkpoints/ckpt_7.pth'

# training
device_id: 0
lr: 0.001
optimizer: 'adam'
nepochs: 100
save_freq: 10
output_dir: 'outputs/train'

# random 
seed: 2024